name: Lint

on:
  push:

permissions:
  contents: write

jobs:
  quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: mbstring, pdo, pdo_mysql, fileinfo

      - name: Install Dependencies (skip pubkey check)
        env:
          COMPOSER_DISABLE_SECURITY_WARNINGS: 1
        run: composer install --no-interaction --no-scripts --prefer-dist

      - name: Run Pint
        run: vendor/bin/pint

      - name: Commit Changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Pint
          commit_options: '--no-verify'
